*** Exception: foo
Stopped at <exception thrown>
_exception :: e = GHC.IOBase.ErrorCall ('f' : _)
Stopped at <exception thrown>
_exception :: e = ErrorCall ('f' : _)
-1  : main (../Test7.hs:2:17-27)
-2  : main (../Test7.hs:2:7-28)
<end of history>
Logged breakpoint at ../Test7.hs:2:17-27
_result :: a
Logged breakpoint at ../Test7.hs:2:7-28
_result :: IO a
no more logged breakpoints
Logged breakpoint at ../Test7.hs:2:17-27
_result :: a
Stopped at <exception thrown>
_exception :: e
already at the beginning of the history
_exception = ErrorCall ['f','o','o']
_exception :: Exception = ErrorCall ['f','o','o']
_result :: a = _
*** Exception: foo
*** Exception: foo
