Stopped at <exception thrown>
_exception :: e = GHC.IOBase.ErrorCall ('a' : _)
()
